name: Portfolio Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: [self-hosted, dev2-server]
    steps:
    - uses: actions/checkout@v2

    - name: Grab the code
      run: |
        cd /home/zubairhassan652/portfolio
        git pull   
        
    - name: Nodejs build react app
      run: |
        cd /home/zubairhassan652/portfolio
        npm run build